common: &common
  username: peterto
  password:
  adapter: postgresql
  host: localhost
  port: 5432

aaron:
  <<: *common
  username: postgres
  password: batman
  database: blogarr_development

development: 
  <<: *common
  database: blogarr_development

test:
  <<: *common
  database: blogarr_test

production:
  <<: *common
  database: blogarr_production
